### ISSUE TITLE
Cannot extract data from alfresco

### ISSUE THREAD

**Issue by bpechcorp** [fcorti/Alflytics#16] opened 2018-09-14 15:16 UTC
I have install alflytics manual with postgresql 9.4. 
When i extract data, nothing extracted. And in log has an error below:
2018/09/14 22:12:44 - alflyticsExtract - Dispatching started for transformation [alflyticsExtract]
2018/09/14 22:12:44 - Data Grid.0 - Finished processing (I=0, O=0, R=0, W=1, U=0, E=0)
2018/09/14 22:12:44 - Variable substitution.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
2018/09/14 22:12:54 - HTTP Client.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Because of an error, this step can't continue:
2018/09/14 22:12:54 - HTTP Client.0 - Unable to get result from specified URL : http://103.237.144.27:9080/pentaho/api/repos/:public:Alflytics:ETL:Get%20all.kjb/viewer
2018/09/14 22:12:54 - HTTP Client.0 - The host did not accept the connection within timeout of 10000 ms
2018/09/14 22:12:54 - HTTP Client.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
2018/09/14 22:12:54 - alflyticsExtract - Transformation detected one or more steps with errors.
2018/09/14 22:12:54 - alflyticsExtract - Transformation is killing the other steps!

**Comment by fcorti** [comment] 2018-09-19 07:15
Hi,

I think the error is quite clear:
The host did not accept the connection within timeout of 10000 ms

Do you have any firewall or something preventing you to access to the server?

**Comment by bpechcorp** [comment] 2018-09-19 07:29
Hi @fcorti ,
I don't have any firewall, i use PDI to extract and view db, i see data in "OPE_ALF_USERS" table.
But other tables is empty.

**Comment by fcorti** [comment] 2018-09-19 07:41
This behaviour does not match with the previous error.
If you see data into the USERs' table, you cannot have a connection timeout.
Maybe you are referring to two different errors?
If I am correct please close this and open another with the description of the error and further details on the environment.
Many thanks.

**Comment by bpechcorp** [comment] 2018-09-19 08:34
@fcorti , 
Sorry, i described unclear, 
- First case: extract use http://x.x.x.x:xx/pentaho/plugin/Alflytics/api/extract , and no data on db
- Second Case: Extract use PDI: there are data on some tables . But  Alflytics Dashboard is empty : https://drive.google.com/open?id=1w2qzmf4VhvbeuDnvw_Jq-z4nRF6lyGbx

**Comment by fcorti** [comment] 2018-09-19 08:47
Please, let's face the issues in two different tickets.
Please keep the first here and open another for the second issue.

About this issue (issue n.1 in your list), I assume the log is what you reported above.
If this is true, the problem is the timeout of the server.

**Comment by marcogianini** [comment] 2019-03-19 19:20
Hi 
I have the both issues. 
I installed Pentaho in same server of Alfresco but each one in different ports. Alfresco was in 8080 and Pentaho 9090. Only change in Pentaho with Alflytics the server.xml file to 9090 port.
The issues are:
- when i execute extract in Alflytics nothing run, in log show me about http://localhost:8080/pentaho and I don´t find the file that has this configuration.
- and dashboard was blank but browse i see the reports public of Alfresco.
Thanks in help me.

**Comment by fcorti** [comment] 2019-03-24 08:06
Ciao Marco,

By default Alflytics works on port 8080.
You can change the port directly into the "Get All" job using Spoon.
If you check into the parameters you will find one called port with the default value to 8080.
Change it to 9090, save it an run it again.

I hope this will help you.

**Closed as completed by fcorti** 2019-03-24 08:06 UTC
Labels: question
