### ISSUE TITLE
Error importing the audit event.

### ISSUE THREAD

**Issue by Roberto-Bicudo** [fcorti/Alflytics#15] opened 2018-08-10 22:10 UTC
Corti, good evening.
I am with problems in extraction:

018/08/10 18:37:07 - Write to log.0 - ------------> Linenr 33077------------------------------
2018/08/10 18:37:07 - Write to log.0 - Error importing the audit event.
2018/08/10 18:37:07 - Write to log.0 - Probably the ID is extracted multiple times but at the moment this is how Alfresco works.
2018/08/10 18:37:07 - Write to log.0 - 
2018/08/10 18:37:07 - Write to log.0 - entry = '{"id":90260,"application":"alfresco-access","user":"admin","time":"2015-11-07T23:30:59.467-02:00","values":{"\/alfresco-access\/login\/user":"admin"}}'
2018/08/10 18:37:07 - Write to log.0 - fileName = 'source.1.fromId.90000.maxItems.5000.json'
2018/08/10 18:37:07 - Write to log.0 - filePath = /home/opt/pentaho-server/tomcat/temp/Alflytics/Alfresco/AuditTrail/alfresco-access
2018/08/10 18:37:07 - Write to log.0 - instanceId = 1
2018/08/10 18:37:07 - Write to log.0 - id = 90260
2018/08/10 18:37:07 - Write to log.0 - application = 'alfresco-access'

I have't idea how to solve.

Could you help me?

Thank you.

Roberto

**Comment by fcorti** [comment] 2018-08-11 17:21
Hi Roberto,

This is not an error but a warning.
The warning highlights what sometimes happen on Alfresco side, often because of indexing.
The suggestion is to ignore the warning, if you don't mid to be precise at 100% on the analytics or try to solve it on Alfresco side.
One thing to do is reindex Solr.
I'm aware that in other cases it helps.

I close the issue because not a bug of Alflytics, but an issue related to Alfresco extraction.

Feel free to ask more, if required.

**Closed as completed by fcorti** 2018-08-11 17:21 UTC
Labels: question

**Comment by Roberto-Bicudo** [comment] 2018-08-14 17:50
Francesco
Thank you for answering me.
I understood that reindex SOLR4.
I will try it.
Sorry, but maybe I do more questions to you.
I´m trying to migrate form "AAAR" to "Alflytics".
Sincery,
Roberto Bicudo
    Em ‎sábado‎, ‎11‎ de ‎agosto‎ de ‎2018‎ ‎14‎:‎21‎:‎32‎ ‎-03, Francesco Corti <notifications@github.com> escreveu:  
 
 
Hi Roberto,

This is not an error but a warning.
The warning highlights what sometimes happen on Alfresco side, often because of indexing.
The suggestion is to ignore the warning, if you don't mid to be precise at 100% on the analytics or try to solve it on Alfresco side.
One thing to do is reindex Solr.
I'm aware that in other cases it helps.

I close the issue because not a bug of Alflytics, but an issue related to Alfresco extraction.

Feel free to ask more, if required.

**Comment by fcorti** [comment] 2018-08-16 06:52
Hi Roberto,

Can you please open another question about it?
The answer is not exciting but can help other developers.

Many thanks.
